name: Proposal for an Amendment
description: Proposal for amendments to WMO Manual on Codes (WMO-No.306), vI.2 that may be submitted for WMO approval with the standard or fast-track approval procedure.
title: "[Enter table name, number and a very brief description of change]"
body:
  - type: markdown
    attributes:
      value: The content in this issue will be kept up to date during the drafting of the proposal. Please pay attention to accuracy, spelling and grammar as it may be referenced.
  - type: textarea  
    id: introduction
    attributes:
      label: Introduction
      description: Overview description of the amendment(s). Include as much relevant information possible, such as rationale, purpose, and implementation plans. 
    validations:
      required: true
  - type: textarea
    id: amendment-details
    attributes:
      label: Amendment details 
      description: Tables of the exact changes proposed with minimal descriptive information. This content may evolve as the proposal is finalized. Convert CSV to Markdown at https://www.convertcsv.com/csv-to-markdown.htm
    validations:
      required: true
  - type: textarea
    id: requestor
    attributes:
      label: Requestor(s)
      description: Individuals, groups, or organizations that are requesting the amendment. Include relevant affiliations and GitHub user names, as applicable.
    validations:
      required: true
  - type: textarea
    id: stakeholder
    attributes:
      label: Stakeholder(s)
      description: Individuals, groups, or organizations that have an interest or may be impacted by the amendment. Include relevant affiliations and GitHub user names, as applicable.
  - type: dropdown
    attributes:
      label: Expected impact of change
      description: Choose LOW (for editorial changes to existing codes), MEDIUM (for new codes) or HIGH (for deprecated and superseded codes)
      multiple: false
      options:
        - "LOW"
        - "MEDIUM"
        - "HIGH"
  - type: textarea
    id: consultations
    attributes:
      label: Consultations
      description: Individuals, groups,or organizations that are consulted. Also cite publications or other documents as references. Include relevant affiliations, GitHub user names, and URLS as applicable.
  - type: textarea
    attributes:
      label: Data exchange plans
      description: Describe plans for data exchange associated with the proposal. For example, identify relevant datasets, WMO systems (WIGOS, WIS2, WIPPS), timelines, etc. 
  - type: textarea
    attributes:
      label: Comments
      description: Other information that may be informative and relevant.
