#!/usr/bin/env python

import sys
import string
import csv
import re
import os

version = sys.argv[1]
dir = sys.argv[2]

infilename = dir+'/BUFR_'+version+'_TableC_en.txt'
outfilename = 'BUFR_TableC_en.csv'

with open(infilename, encoding = 'utf-8') as csvFile:
    csvReader = csv.reader(csvFile, delimiter = ',', quotechar='"')
    outfile = open(outfilename, 'w', encoding='utf-8', newline='')
    outfilewriter = csv.writer(outfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    for row in csvReader:
        outfilewriter.writerow(row[1:])

    outfile.close()
