#!/usr/bin/env python

import sys
import string
import csv
from os.path import basename
from os.path import splitext


infilename = sys.argv[1]

with open(infilename, encoding = 'utf-8') as csvFile:
    csvReader = csv.reader(csvFile, delimiter = ',', quotechar='"')
    lineCount = 0
    category = "--"
    for row in csvReader:
        if lineCount == 0:
            columnNames=row
            lineCount += 1
        else:
            #if category != row[0][1:3]:
            if category != row[0]:
                try:
                    outfile.close()
                except:
                    print('')
                #category = row[0][1:3]
                category = row[0]
                print('category='+category)
                outfilename = splitext(infilename)[0]+'_'+category+'.csv'
                outfile = open(outfilename, 'w', encoding='utf-8', newline='')
                outfilewriter = csv.writer(outfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                outfilewriter.writerow(columnNames)

            outfilewriter.writerow(row)
            lineCount += 1

    outfile.close()
    print(f'Processed {lineCount} lines.')
