#!/usr/bin/env python

import sys
import string
import csv
from os.path import basename
from os.path import splitext

version = sys.argv[1]
dir = sys.argv[2]

infilename = dir+'/BUFRCREX_'+version+'_TableB_en.txt'

with open(infilename, encoding = 'utf-8') as csvFile:
    csvReader = csv.reader(csvFile, delimiter = ',', quotechar='"')
    lineCount = 0
    category = "--"
    for row in csvReader:
        if lineCount == 0:
            columnNames=row[1:]
            lineCount += 1
        else:
            #if category != row[0][1:3]:
            if category != row[1]:
                try:
                    outfile.close()
                except:
                    print('')
                #category = row[0][1:3]
                category = row[1]
                print('category='+category)
                outfilename = 'BUFRCREX_TableB_en_'+category+'.csv'
                outfile = open(outfilename, 'w', encoding='utf-8', newline='')
                outfilewriter = csv.writer(outfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL,lineterminator='\n')
                outfilewriter.writerow(columnNames)

            outfilewriter.writerow(row[1:])
            lineCount += 1

    outfile.close()
    print(f'Processed {lineCount} lines.')
