name: CI

on:
  push:
    paths: 
      - '*.csv'

jobs:
  make_xml:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}
    - name: create xml files and push
      run: | 
        scripts/makeLegacyFormats.sh
        ls txt
        ls xml
        git config --global user.email "efucile@wmo.int"
        git config --global user.name "Enrico Fucile"
        git branch
        # Use of status --pocelain to check if files have been changed or not
        # If changes commit and push
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -m "xml,txt files" -a
          git push
        # if not, only print a message saying not commit
        else
          echo "No changes to commit"
        fi
